content/jtable/jTableDemos/JTableMvcDemos/Controllers/DemoController.cs
using System.Web.Mvc;
using System.Web.SessionState;
using System.Linq;

namespace CrudPlugInDevelop.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class DemoController : RepositoryBasedController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PagingAndSorting()
        {
            return View();
        }

        public ActionResult SelectingRows()
        {
            return View();
        }

        public ActionResult MasterChild()
        {
            return View();
        }

        public ActionResult UsingWithValidationEngine1()
        {
            return View();            
        }

        public ActionResult UsingWithValidationEngine2()
        {
            return View();
        }

        public ActionResult Theme()
        {
            return View();            
        }

        public ActionResult TurkishLocalization()
        {
            return View();            
        }

        public ActionResult Filtering()
        {
            var cities = _repository.CityRepository.GetAllCities().Select(city => new SelectListItem {Text = city.CityName, Value = city.CityId.ToString()}).ToList();
            cities.Insert(0, new SelectListItem {Selected = true, Text = "All cities", Value = "0"});

            ViewBag.Cities = cities;
            return View();
        }

        public ActionResult ColumnResizing()
        {
            return View();
        }

        public ActionResult ColumnHideShow()
        {
            return View();
        }
    }
}

content/jtable/jTableDemos/JTableMvcDemos/Views/Demo/ColumnHideShow.cshtml
@{
    ViewBag.Title = "Column hide/show demo";
}
<div id="StudentTableContainer">
</div>
<script type="text/javascript">

    $(document).ready(function () {

        $('#StudentTableContainer').jtable({
            tableId: 'MyDemoTable',
            title: 'Student List',
            paging: true,
            sorting: true,
            columnResizable: true, //Actually, no need to set true since it's default.
            columnSelectable: true, //Actually, no need to set true since it's default.
            saveUserPreferences: true, //Actually, no need to set true since it's default.
            defaultSorting: 'Name ASC',
            actions: {
                listAction: '@Url.Action("StudentList")',
                deleteAction: '@Url.Action("DeleteStudent")',
                updateAction: '@Url.Action("UpdateStudent")',
                createAction: '@Url.Action("CreateStudent")'
            },
            fields: {
                StudentId: {
                    key: true,
                    create: false,
                    edit: false,
                    title: 'Id',
                    width: '5%',
                    sorting: false,
                    list: false
                },
                Name: {
                    title: 'Name',
                    width: '20%',
                    visibility: 'fixed' //This column always will be shown
                },
                EmailAddress: {
                    title: 'Email address',
                    width: '20%',
                    list: true
                },
                Password: {
                    title: 'User Password',
                    type: 'password',
                    list: false
                },
                Gender: {
                    title: 'Gender',
                    width: '13%',
                    options: { 'M': 'Male', 'F': 'Female' },
                    list: true,
                    visibility: 'hidden' //Hide this column as default
                },
                CityId: {
                    title: 'City',
                    width: '12%',
                    options: '@Url.Action("GetCityOptions")',
                    list: false
                },
                BirthDate: {
                    title: 'Birth date',
                    width: '30%',
                    type: 'date',
                    displayFormat: 'yy-mm-dd'
                },
                Education: {
                    title: 'Education',
                    list: false,
                    type: 'radiobutton',
                    options: { '1': 'Primary school', '2': 'High school', '3': 'University' }
                },
                About: {
                    title: 'About this person',
                    type: 'textarea',
                    list: false
                },
                IsActive: {
                    title: 'Status',
                    width: '12%',
                    type: 'checkbox',
                    values: { 'false': 'Passive', 'true': 'Active' },
                    defaultValue: 'true',
                    list: false
                },
                RecordDate: {
                    title: 'Record date',
                    width: '30%',
                    type: 'date',
                    displayFormat: 'yy-mm-dd',
                    create: false,
                    edit: false,
                    sorting: false //This column is not sortable!
                }
            }
        });

        //Load student list from server
        $('#StudentTableContainer').jtable('load');

    });

</script>
<br />
<hr />
<h3>
    HTML code</h3>
<pre class="brush:html">&lt;div id=&quot;StudentTableContainer&quot;&gt;&lt;/div&gt;</pre>
<h3>
    Javascript code</h3>
<pre class="brush:js; highlight: [10,11,12,33,50]">&lt;script type=&quot;text/javascript&quot;&gt;

    $(document).ready(function () {

        $(&#39;#StudentTableContainer&#39;).jtable({
            tableId: &#39;MyDemoTable&#39;,
            title: &#39;Student List&#39;,
            paging: true,
            sorting: true,
            columnResizable: true, //Actually, no need to set true since it&#39;s default
            columnSelectable: true, //Actually, no need to set true since it&#39;s default
            saveUserPreferences: true, //Actually, no need to set true since it&#39;s default
            defaultSorting: &#39;Name ASC&#39;,
            actions: {
                listAction: &#39;/Demo/StudentList&#39;,
                deleteAction: &#39;/Demo/DeleteStudent&#39;,
                updateAction: &#39;/Demo/UpdateStudent&#39;,
                createAction: &#39;/Demo/CreateStudent&#39;
            },
            fields: {
                StudentId: {
                    key: true,
                    create: false,
                    edit: false,
                    title: &#39;Id&#39;,
                    width: &#39;5%&#39;,
                    sorting: false,
                    list: false
                },
                Name: {
                    title: &#39;Name&#39;,
                    width: &#39;20%&#39;,
                    visibility: &#39;fixed&#39; //This column always will be shown
                },
                EmailAddress: {
                    title: &#39;Email address&#39;,
                    width: &#39;20%&#39;,
                    list: true
                },
                Password: {
                    title: &#39;User Password&#39;,
                    type: &#39;password&#39;,
                    list: false
                },
                Gender: {
                    title: &#39;Gender&#39;,
                    width: &#39;13%&#39;,
                    options: { &#39;M&#39;: &#39;Male&#39;, &#39;F&#39;: &#39;Female&#39; },
                    list: true,
                    visibility: &#39;hidden&#39; //Hide this column as default
                },
                CityId: {
                    title: &#39;City&#39;,
                    width: &#39;12%&#39;,
                    options: &#39;/Demo/GetCityOptions&#39;
                    list: false
                },
                BirthDate: {
                    title: &#39;Birth date&#39;,
                    width: &#39;30%&#39;,
                    type: &#39;date&#39;,
                    displayFormat: &#39;yy-mm-dd&#39;
                },
                Education: {
                    title: &#39;Education&#39;,
                    list: false,
                    type: &#39;radiobutton&#39;,
                    options: { &#39;1&#39;: &#39;Primary school&#39;, &#39;2&#39;: &#39;High school&#39;, &#39;3&#39;: &#39;University&#39; }
                },
                About: {
                    title: &#39;About this person&#39;,
                    type: &#39;textarea&#39;,
                    list: false
                },
                IsActive: {
                    title: &#39;Status&#39;,
                    width: &#39;12%&#39;,
                    type: &#39;checkbox&#39;,
                    values: { &#39;false&#39;: &#39;Passive&#39;, &#39;true&#39;: &#39;Active&#39; },
                    defaultValue: &#39;true&#39;,
                    list: false
                },
                RecordDate: {
                    title: &#39;Record date&#39;,
                    width: &#39;30%&#39;,
                    type: &#39;date&#39;,
                    displayFormat: &#39;yy-mm-dd&#39;,
                    create: false,
                    edit: false,
                    sorting: false //This column is not sortable!
                }
            }
        });

        //Load student list from server
        $(&#39;#StudentTableContainer&#39;).jtable(&#39;load&#39;);

    });

&lt;/script&gt;</pre>
<h3>
    Server side code</h3>
@Html.Partial("_PagedAndSortedServerSideCodes")

<p>Right click the table header to select columns. Column hide/show is enabled as default.</p>

content/jtable/jTableDemos/JTableMvcDemos/Views/Demo/ColumnResizing.cshtml
@{
    ViewBag.Title = "Column resizing demo";
}
<div id="StudentTableContainer">
</div>
<script type="text/javascript">

    $(document).ready(function () {

        $('#StudentTableContainer').jtable({
            tableId: 'MyResizableTable',
            title: 'Student List',
            paging: true,
            pageSize: 10,
            sorting: true,
            //columnResizable: true, //No need to set true since it's default.
            defaultSorting: 'Name ASC',
            actions: {
                listAction: '@Url.Action("StudentList")',
                deleteAction: '@Url.Action("DeleteStudent")',
                updateAction: '@Url.Action("UpdateStudent")',
                createAction: '@Url.Action("CreateStudent")'
            },
            fields: {
                StudentId: {
                    key: true,
                    create: false,
                    edit: false,
                    title: 'Id',
                    width: '5%',
                    sorting: false,
                    list: false
                },
                Name: {
                    title: 'Name',
                    width: '20%'
                },
                EmailAddress: {
                    title: 'Email address',
                    width: '20%',
                    list: false
                },
                Password: {
                    title: 'User Password',
                    type: 'password',
                    list: false
                },
                Gender: {
                    title: 'Gender',
                    width: '13%',
                    options: { 'M': 'Male', 'F': 'Female' },
                    list: false
                },
                CityId: {
                    title: 'City',
                    width: '12%',
                    options: '@Url.Action("GetCityOptions")',
                    list: false
                },
                BirthDate: {
                    title: 'Birth date',
                    width: '30%',
                    type: 'date',
                    displayFormat: 'yy-mm-dd'
                },
                Education: {
                    title: 'Education',
                    list: false,
                    type: 'radiobutton',
                    options: { '1': 'Primary school', '2': 'High school', '3': 'University' }
                },
                About: {
                    title: 'About this person',
                    type: 'textarea',
                    list: false
                },
                IsActive: {
                    title: 'Status',
                    width: '12%',
                    type: 'checkbox',
                    values: { 'false': 'Passive', 'true': 'Active' },
                    defaultValue: 'true',
                    list: false
                },
                RecordDate: {
                    title: 'Record date',
                    width: '30%',
                    type: 'date',
                    displayFormat: 'yy-mm-dd',
                    create: false,
                    edit: false,
                    sorting: false //This column is not sortable!
                }
            }
        });

        //Load student list from server
        $('#StudentTableContainer').jtable('load');

    });

</script>


content/jtable/jTableDemos/JTableMvcDemos/Views/Demo/Filtering.cshtml
@{
    ViewBag.Title = "Filtering Demo";
}

@section CssImport{
    <style>
        div.filtering
        {
            border: 1px solid #999;
            margin-bottom: 5px;
            padding: 10px;
            background-color: #EEE;
        }
    </style>
}

<div class="filtering">
    <form>
        <label>Name: <input type="text" name="name" id="name" /></label>
        <label>City: @Html.DropDownList("cityId", (IEnumerable<SelectListItem>)ViewBag.Cities, new { id = "cityId" })</label>
        <button type="submit" id="LoadRecordsButton">Load records</button>
    </form>
</div>

<div id="StudentTableContainer"></div>
<script type="text/javascript">

    $(document).ready(function () {

        $('#StudentTableContainer').jtable({
            title: 'Student List',
            paging: true,
            pageSize: 10,
            sorting: true,
            defaultSorting: 'Name ASC',
            actions: {
                listAction: '@Url.Action("StudentListByFiter")',
                deleteAction: '@Url.Action("DeleteStudent")',
                updateAction: '@Url.Action("UpdateStudent")',
                createAction: '@Url.Action("CreateStudent")'
            },
            fields: {
                StudentId: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                Name: {
                    title: 'Name',
                    width: '23%'
                },
                EmailAddress: {
                    title: 'Email address',
                    list: false
                },
                Password: {
                    title: 'User Password',
                    type: 'password',
                    list: false
                },
                Gender: {
                    title: 'Gender',
                    width: '13%',
                    options: { 'M': 'Male', 'F': 'Female' }
                },
                CityId: {
                    title: 'City',
                    width: '12%',
                    options: '@Url.Action("GetCityOptions")'
                },
                BirthDate: {
                    title: 'Birth date',
                    width: '15%',
                    type: 'date',
                    displayFormat: 'yy-mm-dd'
                },
                Education: {
                    title: 'Education',
                    list: false,
                    type: 'radiobutton',
                    options: { '1': 'Primary school', '2': 'High school', '3': 'University' }
                },
                About: {
                    title: 'About this person',
                    type: 'textarea',
                    list: false
                },
                IsActive: {
                    title: 'Status',
                    width: '12%',
                    type: 'checkbox',
                    values: { 'false': 'Passive', 'true': 'Active' },
                    defaultValue: 'true'
                },
                RecordDate: {
                    title: 'Record date',
                    width: '15%',
                    type: 'date',
                    displayFormat: 'dd.mm.yy',
                    create: false,
                    edit: false,
                    sorting: false //This column is not sortable!
                }
            }
        });

        //Re-load records when user click 'load records' button.
        $('#LoadRecordsButton').click(function (e) {
            e.preventDefault();
            $('#StudentTableContainer').jtable('load', {
                name: $('#name').val(),
                cityId: $('#cityId').val()
            });
        });

        //Load all records when page is first shown
        $('#LoadRecordsButton').click();
    });

</script>
<br />
<hr />
<h3>
    HTML code</h3>
<pre class="brush:html">&lt;div class=&quot;filtering&quot;&gt;
    &lt;form&gt;
        Name: &lt;input type=&quot;text&quot; name=&quot;name&quot; id=&quot;name&quot; /&gt;
        City: 
        &lt;select id=&quot;cityId&quot; name=&quot;cityId&quot;&gt;
            &lt;option selected=&quot;selected&quot; value=&quot;0&quot;&gt;All cities&lt;/option&gt;
            &lt;option value=&quot;1&quot;&gt;Adana&lt;/option&gt;
            &lt;option value=&quot;2&quot;&gt;Ankara&lt;/option&gt;
            &lt;option value=&quot;3&quot;&gt;Athens&lt;/option&gt;
            &lt;option value=&quot;4&quot;&gt;Beijing&lt;/option&gt;
            &lt;option value=&quot;5&quot;&gt;Berlin&lt;/option&gt;
            &lt;option value=&quot;6&quot;&gt;Bursa&lt;/option&gt;
            &lt;option value=&quot;7&quot;&gt;İstanbul&lt;/option&gt;
            &lt;option value=&quot;8&quot;&gt;London&lt;/option&gt;
            &lt;option value=&quot;9&quot;&gt;Madrid&lt;/option&gt;
            &lt;option value=&quot;10&quot;&gt;Mekke&lt;/option&gt;
            &lt;option value=&quot;11&quot;&gt;New York&lt;/option&gt;
            &lt;option value=&quot;12&quot;&gt;Paris&lt;/option&gt;
            &lt;option value=&quot;13&quot;&gt;Samsun&lt;/option&gt;
            &lt;option value=&quot;14&quot;&gt;Trabzon&lt;/option&gt;
            &lt;option value=&quot;15&quot;&gt;Volos&lt;/option&gt;
        &lt;/select&gt;
        &lt;button type=&quot;submit&quot; id=&quot;LoadRecordsButton&quot;&gt;Load records&lt;/button&gt;
    &lt;/form&gt;
&lt;/div&gt;

&lt;div id=&quot;StudentTableContainer&quot;&gt;&lt;/div&gt;</pre>
<h3>
    Javascript code</h3>
<pre class="brush:js; highlight: [11,82,83,84,85,86,87,88,89,91,92]">&lt;script type=&quot;text/javascript&quot;&gt;

    $(document).ready(function () {

        $(&#39;#StudentTableContainer&#39;).jtable({
            title: &#39;Student List&#39;,
            paging: true,
            sorting: true,
            defaultSorting: &#39;Name ASC&#39;,
            actions: {
                listAction: &#39;/Demo/StudentListByFiter&#39;,
                deleteAction: &#39;/Demo/DeleteStudent&#39;,
                updateAction: &#39;/Demo/UpdateStudent&#39;,
                createAction: &#39;/Demo/CreateStudent&#39;
            },
            fields: {
                StudentId: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                Name: {
                    title: &#39;Name&#39;,
                    width: &#39;23%&#39;
                },
                EmailAddress: {
                    title: &#39;Email address&#39;,
                    list: false
                },
                Password: {
                    title: &#39;User Password&#39;,
                    type: &#39;password&#39;,
                    list: false
                },
                Gender: {
                    title: &#39;Gender&#39;,
                    width: &#39;13%&#39;,
                    options: { &#39;M&#39;: &#39;Male&#39;, &#39;F&#39;: &#39;Female&#39; }
                },
                CityId: {
                    title: &#39;City&#39;,
                    width: &#39;12%&#39;,
                    options: &#39;/Demo/GetCityOptions&#39;
                },
                BirthDate: {
                    title: &#39;Birth date&#39;,
                    width: &#39;15%&#39;,
                    type: &#39;date&#39;,
                    displayFormat: &#39;yy-mm-dd&#39;
                },
                Education: {
                    title: &#39;Education&#39;,
                    list: false,
                    type: &#39;radiobutton&#39;,
                    options: { &#39;1&#39;: &#39;Primary school&#39;, &#39;2&#39;: &#39;High school&#39;, &#39;3&#39;: &#39;University&#39; }
                },
                About: {
                    title: &#39;About this person&#39;,
                    type: &#39;textarea&#39;,
                    list: false
                },
                IsActive: {
                    title: &#39;Status&#39;,
                    width: &#39;12%&#39;,
                    type: &#39;checkbox&#39;,
                    values: { &#39;false&#39;: &#39;Passive&#39;, &#39;true&#39;: &#39;Active&#39; },
                    defaultValue: &#39;true&#39;
                },
                RecordDate: {
                    title: &#39;Record date&#39;,
                    width: &#39;15%&#39;,
                    type: &#39;date&#39;,
                    displayFormat: &#39;dd.mm.yy&#39;,
                    create: false,
                    edit: false,
                    sorting: false //This column is not sortable!
                }
            }
        });

        //Re-load records when user click &#39;load records&#39; button.
        $(&#39;#LoadRecordsButton&#39;).click(function (e) {
            e.preventDefault();
            $(&#39;#StudentTableContainer&#39;).jtable(&#39;load&#39;, {
                name: $(&#39;#name&#39;).val(),
                cityId: $(&#39;#cityId&#39;).val()
            });
        });

        //Load all records when page is first shown
        $(&#39;#LoadRecordsButton&#39;).click();
    });

&lt;/script&gt;</pre>
<h3>
    Server side code</h3>
@Html.Partial("_FilteredPagedAndSortedServerSideCodes")


content/jtable/jTableDemos/JTableMvcDemos/Views/Demo/Index.cshtml
@{
    ViewBag.Title = "jTable Demos-Examples";
}
@section CssImport 
{
    <style type="text/css">
        ul#DemoList > li
        {
            font-weight: bold;
        }
        
        ul#DemoList ul
        {
            font-weight: normal;
        }
    </style>
}
<h2>
    Demos</h2>
<ul id="DemoList">
    <li>Paging & Sorting<ul>
        <li>@Html.ActionLink("Paging and sorting", "PagingAndSorting")</li></ul>
    </li>
    <li>Selecting<ul>
        <li>@Html.ActionLink("Selecting rows", "SelectingRows")</li></ul>
    </li>
    <li>Master/Child tables<ul>
        <li>@Html.ActionLink("Master/Child tables", "MasterChild")</li></ul>
    </li>
    <li>Filtering<ul>
        <li>@Html.ActionLink("Filtering records", "Filtering")</li></ul>
    </li>
    <li>Validation<ul>
        <li>@Html.ActionLink("Using with 'validation engine' plugin", "UsingWithValidationEngine1")</li>
        <li>@Html.ActionLink("Using with 'validation engine' plugin (easy way)", "UsingWithValidationEngine2")</li>
    </ul>
    </li>
    <li>Localization<ul>
        <li>@Html.ActionLink("A sample localization (Turkish)", "TurkishLocalization")</li></ul>
    </li>
    <li>Others<ul>
        <li>@Html.ActionLink("Column resizing", "ColumnResizing")</li>
        <li>@Html.ActionLink("Column hide/show", "ColumnHideShow")</li></ul>
    </li>
    <li>Themes<ul>
        <li><a href="@Url.Action("Theme", "Demo")?jTableStyle=standard/blue/jtable_blue.css">Blue theme</a></li>
        <li><a href="@Url.Action("Theme", "Demo")?jTableStyle=standard/red/jtable_red.css">Red theme</a></li>
        <li><a href="@Url.Action("Theme", "Demo")?jTableStyle=standard/green/jtable_green.css">Green theme</a></li>
        <li><a href="@Url.Action("Theme", "Demo")?jTableStyle=standard/purple/jtable_purple.css">Purple theme</a></li>
    </ul>
    </li>
</ul>

content/jtable/jTableDemos/JTableMvcDemos/Views/Demo/Theme.cshtml
@{
    ViewBag.Title = "Theme Demo";
}
@section CssImport 
{
    <style type="text/css">
        #SelectedRowList
        {
            margin-top: 5px;
            border: 1px solid #999;
            background-color: #EEE;
            padding: 5px;
        }
    </style>
}

<!-- Container for jTable -->
<div id="StudentTableContainer"></div>

<script type="text/javascript">

    $(document).ready(function () {

        //Prepare jtable plugin
        $('#StudentTableContainer').jtable({
            title: 'Student List',
            paging: true,
            sorting: true,
            defaultSorting: 'Name ASC',
            selecting: true, //Enable selecting
            multiselect: true, //Allow multiple selecting
            selectingCheckboxes: true, //Show checkboxes on first column
            //selectOnRowClick: false, //Enable this to only select using checkboxes
            actions: {
                listAction: '@Url.Action("StudentList")',
                deleteAction: '@Url.Action("DeleteStudent")',
                updateAction: '@Url.Action("UpdateStudent")',
                createAction: '@Url.Action("CreateStudent")'
            },
            fields: {
                StudentId: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                Name: {
                    title: 'Name',
                    width: '23%',
                    inputClass: 'validate[required]'
                },
                EmailAddress: {
                    title: 'Email address',
                    list: false,
                    inputClass: 'validate[required,custom[email]]'
                },
                Password: {
                    title: 'User Password',
                    type: 'password',
                    list: false,
                    inputClass: 'validate[required]'
                },
                Gender: {
                    title: 'Gender',
                    width: '13%',
                    options: { 'M': 'Male', 'F': 'Female' }
                },
                CityId: {
                    title: 'City',
                    width: '12%',
                    options: '@Url.Action("GetCityOptions")'
                },
                BirthDate: {
                    title: 'Birth date',
                    width: '15%',
                    type: 'date',
                    displayFormat: 'yy-mm-dd',
                    inputClass: 'validate[required,custom[date]]'
                },
                Education: {
                    title: 'Education',
                    list: false,
                    type: 'radiobutton',
                    options: { '1': 'Primary school', '2': 'High school', '3': 'University' },
                    inputClass: 'validate[required]'
                },
                About: {
                    title: 'About this person',
                    type: 'textarea',
                    list: false
                },
                IsActive: {
                    title: 'Status',
                    width: '12%',
                    type: 'checkbox',
                    values: { 'false': 'Passive', 'true': 'Active' },
                    defaultValue: 'true'
                },
                RecordDate: {
                    title: 'Record date',
                    width: '15%',
                    type: 'date',
                    displayFormat: 'yy-mm-dd',
                    create: false,
                    edit: false,
                    sorting: false
                }
            }
        });

        //Load student list from server
        $('#StudentTableContainer').jtable('load');
    });
   
</script>